[project]
name = "practical-deep-learning-for-coders"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastai>=2.8.2",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.5",
]
